package com.pie.utils



class AppConstant {
    companion object {
        const val BASE_URL = "http://pieme.info/"
        const val Authorization = "Authorization"
        const val EXTRA_EMAIL = "EXTRA_EMAIL"
        const val ARG_DATA = "ARG_DATA"
        const val ARG_PIN_CODE = "ARG_PIN_CODE"
        const val ARG_INPUT_VIDEO = "ARG_INPUT_VIDEO"
        const val ARG_PIE_DATA = "ARG_PIE_DATA"
        const val TIME_OUT = 1000L
        const val TYPE_LIKE_POST = "type_like_post"
        const val ARG_PIE_ID="ARG_PIE_ID"
        const val EXTRA_IMAGE_DATA="EXTRA_IMAGE_DATA"
        const val ARG_POS="ARG_POS"
        const val ARG_LIKE_DETAIL="ARG_LIKE_DETAIL"
        const val ARG_DETAIL_DELETE="ARG_DETAIL_DELETE"
        const val ARG_DETAIL_UPDATE="ARG_DETAIL_UPDATE"
        const val ARG_DETAIL_LIKE="ARG_DETAIL_LIKE"
        const val ARG_DETAIL_COMMENT="ARG_DETAIL_COMMENT"
        const val ARG_ISREPLY="ARG_ISREPLY"
        const val ARG_ISLIKE="ARG_ISLIKE"
        const val ARG_POSITION="ARG_POSITION"
        const val WEB_DATE_TYPE="yyyy-MM-dd HH:mm:ss"
        const val DATE_APP_TYPE="dd MMM yy"
        const val TIME_APP_TYPE="h:mm a"
        const val SUGGESTION_LIST="SUGGESTION_LIST"
        const val ARG_ISFROM_PIEDETAIL="ARG_ISFROM_PIEDETAIL"
        const val REQUEST_EDIT_PROFILE=51
        const val IS_EDIT_PROFILE="edit_profile"
        const val ARG_PIE_PROFILE_ID="pie_profile_id"
        const val ARG_PIE_MATE_LIST="piemates_list"
        const val ARG_PIEMATE="pie_mate"
        const val ARG_FOLLOW_STATUS="follow_status"
        const val SETBADGE = "setBadge"
    }
}
const val N_TYPE_FOLLOW = "follow"
const val N_TYPE_UN_FOLLOW = "unfollow"
const val N_TYPE_ACCEPT_FOLLOW = "accept_follow_request"
const val N_TYPE_REJECT_FOLLOW = "reject_follow_request"
const val N_TYPE_FRIEND = "friend"
const val N_TYPE_ACCEPT_FRIEND = "accept_friend_request"
const val N_TYPE_DECLINE_FRIEND = "decline_friend_request"
const val N_TYPE_UN_FRIEND = "unfriend"
const val N_TYPE_LIKE_POST = "like_post"
const val N_TYPE_COMMENT_POST = "comment_post"
const val N_TYPE_COMMENT_REPLY = "comment_reply"
const val N_TYPE_LIKE_COMMENT = "like_comment"
const val N_TYPE_REPORT_POST = "report_post"
const val N_TYPE_GIFT = "gift"
const val N_TYPE_TRANSFER_COIN = "transfer"
const val N_TYPE_PROFILE_VIEW = "profile_view"
const val N_TYPE_REJECT_PAYMENT = "reject_payment"
const val N_TYPE_REFFERAL = "refferal"
const val N_TYPE_REPLY_PROBLEM = "reply_problem"
const val N_TYPE_JUST_JOIN = "just_joined"
const val N_TYPE_BEACTIVE = "beactive"
const val N_TYPE_SHARE_LAST_MONTH_EARNING = "share_last_month_earning"
const val N_TYPE_FRIENDS_LAST_MONTH_EARNING = "friends_last_month_earning"
const val N_TYPE_CANCEL_FRIEND_REQUEST = "cancel_friend_request"
const val N_TYPE_WITHDRAW_COMPLETE = "withdraw_complete"
const val N_TYPE_WITHDRAW_PROCESS = "withdraw_process"
const val N_TYPE_WITHDRAW_REJECT = "withdraw_reject"
const val N_TYPE_SPIN = "spin"
const val N_TYPE_DAILY_REWARD = "daily_reward"
const val N_TYPE_WHO_VIEWED_PROFILE = "whoViewedMyProfile"
const val N_TYPE_GIFT_REDIRECTION = "gift_redirection"
const val N_TYPE_INVITE_FRIEND = "invite_friend"
const val N_TYPE_APP_UPDATE = "app_update"
const val N_TYPE_LINK_REDIRECTION = "link_redirection"
const val N_TYPE_NEW_CONTEST = "new_contest"
const val N_TYPE_CONTEST_RESULT = "contest_result"
const val TYPE_NOTIFY_DATA = "notify_data"


const val N_TYPE_MESSAGE = "message"
const val N_TYPE_BLOCK_USER = "block_user"